version: 2
jobs:
  build:
    working_directory: /home/circleci/my-company-frontend
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout

      - restore_cache:
          key: my-company-frontend-{{ checksum "package.json" }}

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          key: my-company-frontend-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - /home/circleci/my-company/node_modules

      - run:
          name: angular-test
          command: yarn test -- --single-run --no-progress
 
workflows:
  version: 2
  my-company-angular-fe-workflow:
    jobs:
       - build
